### PR TITLE
Delete extra <html> tag

### PR DESCRIPTION
**Pull request by Taki21**
Why cant i straight fowardly commit?

### CODE REVIEW

**Comment by Taki21** [comment]
You Have to change my privallges xD

**Comment by GrimDevs** [comment]
Ok taki

**Comment by Taki21** [comment]
thx

**Comment by GrimDevs** [comment]
I had me you as owner now I forgot that it did not save it so I made you owner ok

**Comment by applqpak** [comment]
That's not an extra tag. It is supposed to be there, as apposed to the proper structure of an HTML5 document.

**Comment by Taki21** [comment]
No...Look <!DOCTYPE **html**> then why <html> again? then its </html>

**Pull request merged**
